/* Plan documents are data only: never execute imported scripts or HTML. */
const ZerkPlans = (() => {
  const text = (value, max = 120) => typeof value === 'string' ? value.trim().slice(0, max) : '';
  function integer(value, min, max, label) {
    if (!Number.isInteger(value) || value < min || value > max) throw Error(`${label}须为 ${min}–${max} 的整数`);
    return value;
  }
  function validate(input) {
    if (!input || input.format !== 'zerk-plan' || input.version !== 1) throw Error('需要 Zerk 计划格式 v1；普通网页、Liftoscript 和训练备份请先转换。');
    if (!text(input.name)) throw Error('计划缺少名称');
    if (!Array.isArray(input.days) || !input.days.length || input.days.length > 12) throw Error('计划需要 1–12 个训练日');
    return {format:'zerk-plan',version:1,name:text(input.name),notes:text(input.notes,2000),source:text(input.source,500),days:input.days.map(day => {
      if (!['back','chest','legs'].includes(day.day)) throw Error('训练日须对应 back、chest 或 legs');
      if (!Array.isArray(day.exercises) || !day.exercises.length || day.exercises.length > 40) throw Error('每个训练日需要 1–40 个动作');
      return {day:day.day,name:text(day.name)||day.day,exercises:day.exercises.map(ex => {
        if (!text(ex.name) || !text(ex.equipment) || !text(ex.part)) throw Error('动作名称、部位和器械不能为空');
        const result={name:text(ex.name),part:text(ex.part),equipment:text(ex.equipment),sets:integer(ex.sets,1,10,'组数'),reps:integer(ex.reps,1,100,'次数'),type:ex.type==='drop'?'drop':'normal',multiplier:ex.multiplier===2?2:1};
        if (result.type==='drop') {
          if (!Array.isArray(ex.segments)||ex.segments.length!==3) throw Error('递减组需要三段重量和次数');
          result.segments=ex.segments.map(s=>{if(typeof s.weight!=='number'||!Number.isFinite(s.weight)||s.weight<0||s.weight>1000)throw Error('递减重量须为 0–1000 kg');return {weight:s.weight,reps:integer(s.reps,1,100,'递减次数')};});
        }
        return result;
      })};
    })};
  }
  function githubURL(value) {
    let url;try{url=new URL(value);}catch{throw Error('请填写 GitHub 计划文件的完整链接');}
    if(url.protocol!=='https:'||url.username||url.password||url.search)throw Error('请使用不含密钥或查询参数的 HTTPS GitHub 文件链接');
    const parts=url.pathname.split('/').filter(Boolean);
    if(url.hostname==='github.com'&&parts.length>=5&&parts[2]==='blob') {
      url=new URL(`https://raw.githubusercontent.com/${parts[0]}/${parts[1]}/${parts.slice(3).join('/')}`);
    }
    if(url.hostname!=='raw.githubusercontent.com'||!url.pathname.endsWith('.json'))throw Error('请选择公开 GitHub 仓库中的 .json 文件链接');
    url.hash='';return url.href;
  }
  return {validate,githubURL};
})();

if(typeof document!=='undefined') (()=>{
  const style=document.createElement('style');
  style.textContent=`#planDialog{max-height:88svh;overflow:auto}#planDialog .modal{padding:18px}#planDialog p{font-size:14px;line-height:1.6;color:var(--muted)}.plan-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.plan-actions button,.plan-actions label{flex:1;min-width:110px;min-height:46px;padding:11px;border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.06);color:var(--text);text-align:center;cursor:pointer;font-size:14px}.plan-entry{margin:10px 0;padding:14px;border:1px solid var(--line);border-radius:16px;background:rgba(255,255,255,.04)}.plan-entry h3{margin:0;font-size:17px}.plan-entry small{font-size:12px;color:var(--muted)}#planMessage{min-height:24px;color:var(--cream)!important}#planPreview input:not([type=checkbox]),#planPreview select,#planURL{width:100%;min-height:46px;background:#16100c;border:1px solid var(--line);border-radius:10px;color:var(--text);padding:8px;font-size:16px}.plan-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.plan-grid label{font-size:14px;color:var(--muted)}.plan-pick{display:flex;gap:10px;align-items:center;margin-bottom:12px;font-size:16px}.plan-pick input{width:24px;height:24px;accent-color:var(--orange)}#planPreview [hidden]{display:none}.plan-preview-name{font-size:20px;margin:15px 0 4px}.plan-day{margin:14px 0;font-size:16px}.plan-link{color:var(--gold)}#planDialog button:disabled{opacity:.5;cursor:wait}`;
  document.head.append(style);
  const modal=document.createElement('dialog');modal.id='planDialog';
  modal.innerHTML=`<section class="modal"><div class="modal-head"><h2>训练计划库</h2><button class="close-modal" id="closePlans" aria-label="关闭计划库">×</button></div><p>保存自己的安排，或导入计划后选择适合你的动作。导入会追加动作，不清除训练历史。</p><div class="plan-actions"><button id="capturePlan">保存当前勾选计划</button><label>导入计划文件<input id="planFile" type="file" accept=".json,application/json" hidden></label></div><details><summary>从 GitHub 更新计划</summary><p>支持公开仓库的 Zerk 格式 JSON 文件。私有仓库请先下载文件，再使用上方导入。更新先预览，不自动改动训练。</p><label for="planURL">GitHub 计划文件链接</label><input id="planURL" type="url" placeholder="https://github.com/用户/仓库/blob/main/plan.json"><div class="plan-actions"><button id="fetchPlan">读取 / 检查更新</button></div></details><p id="planMessage" role="status" aria-live="polite"></p><section id="planSaved"></section><section id="planPreview"></section></section>`;
  document.body.append(modal);
  const get=id=>document.getElementById(id);
  let preview=null,origin='',busy=false;
  const message=value=>get('planMessage').textContent=value;
  function download(plan){const url=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='zerk-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function persist(change){const before=JSON.stringify(state);try{change();if(save())return true;}catch(error){state=JSON.parse(before);throw error;}state=JSON.parse(before);message('保存失败，原训练数据已保留。请先导出备份。');return false;}
  function saved(){const host=get('planSaved');host.replaceChildren();const list=Array.isArray(state.plans)?state.plans:[];if(!list.length){const p=document.createElement('p');p.textContent='还没有保存的计划。先勾选常练动作，再点“保存当前勾选计划”。';host.append(p);}list.forEach((item,index)=>{const card=document.createElement('article');card.className='plan-entry';const title=document.createElement('h3');title.textContent=item.plan.name;card.append(title);const note=document.createElement('p');note.textContent=`${item.plan.days.length} 个训练日 · ${item.updatedAt?new Date(item.updatedAt).toLocaleDateString():'本机保存'}`;card.append(note);const actions=document.createElement('div');actions.className='plan-actions';for(const [label,action] of [['预览 / 使用',()=>show(item.plan,item.url||'')],['导出',()=>download(item.plan)],['移除计划',()=>{if(confirm('只移除此计划，已加入的动作和训练记录仍保留。继续吗？')&&persist(()=>state.plans.splice(index,1)))saved();}]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;actions.append(b);}card.append(actions);host.append(card);});}
  function capture(){const days=Object.entries(DAYS).map(([day,d])=>({day,name:d.title,exercises:allExercises().filter(ex=>(state.selected[day]||[]).includes(ex.id)).map(ex=>{const profile=profileFor(ex.id),draft=draftFor(ex.id,profile);return {name:ex.name,part:ex.part,equipment:ex.equipment,sets:targetFor(ex),reps:Number(draft.reps)||10,type:profile.type,multiplier:profile.multiplier,...(profile.type==='drop'?{segments:draft.segments.map(s=>({weight:Number(s.weight)||0,reps:Number(s.reps)||10}))}:{})};})})).filter(d=>d.exercises.length);if(!days.length)return message('请先在训练页面勾选动作，再保存计划。');show(ZerkPlans.validate({format:'zerk-plan',version:1,name:'我的训练计划',notes:'根据当前勾选动作保存，可在预览中调整。',days}),'');}
  function show(plan,url){preview=ZerkPlans.validate(plan);origin=url;const host=get('planPreview');host.replaceChildren();const nameLabel=document.createElement('label');nameLabel.textContent='计划名称';const name=document.createElement('input');name.id='previewPlanName';name.value=preview.name;name.maxLength=120;nameLabel.append(name);host.append(nameLabel);const note=document.createElement('p');note.textContent=preview.notes;host.append(note);if(preview.source){const source=document.createElement('p');source.textContent='来源：'+preview.source;host.append(source);}preview.days.forEach((day,di)=>{const h=document.createElement('h3');h.className='plan-day';h.textContent=`${day.name} → ${DAYS[day.day].label}`;host.append(h);day.exercises.forEach((ex,ei)=>{const card=document.createElement('article');card.className='plan-entry';card.dataset.di=di;card.dataset.ei=ei;const choose=document.createElement('label');choose.className='plan-pick';const check=document.createElement('input');check.type='checkbox';check.checked=true;check.dataset.pick='';choose.append(check,document.createTextNode(ex.name));card.append(choose);const grid=document.createElement('div');grid.className='plan-grid';for(const [key,label,type] of [['name','动作名称','text'],['equipment','器械','text'],['sets','目标组数','number'],['reps','目标次数','number']]){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.type=type;input.value=ex[key];input.dataset.key=key;if(type==='number'){input.min=1;input.max=key==='sets'?10:100;}else input.maxLength=120;l.append(input);grid.append(l);}card.append(grid);const replace=document.createElement('select');replace.setAttribute('aria-label','用常用动作替换');const opt=document.createElement('option');opt.value='';opt.textContent='替换成常用器械动作…';replace.append(opt);const candidates=[...allExercises().filter(e=>e.day===day.day),...PRESETS[day.day]];candidates.forEach((candidate,i)=>{const o=document.createElement('option');o.value=i;o.textContent=candidate.name+' · '+candidate.equipment;replace.append(o);});replace.onchange=()=>{if(replace.value==='')return;const candidate=candidates[Number(replace.value)];card.querySelector('[data-key=name]').value=candidate.name;card.querySelector('[data-key=equipment]').value=candidate.equipment;ex.part=candidate.part;};card.append(replace);if(ex.type==='drop'){const p=document.createElement('p');p.textContent=`递减组：${ex.segments.map(s=>`${s.weight}kg × ${s.reps}次`).join(' → ')}${ex.multiplier===2?' · 单边重量':''}。三段数值可在训练卡片中修改。`;card.append(p);}host.append(card);});});const actions=document.createElement('div');actions.className='plan-actions';for(const [label,action] of [['只保存到计划库',()=>commit(false)],['保存并加入训练',()=>commit(true)]]){const b=document.createElement('button');b.textContent=label;b.onclick=action;actions.append(b);}host.append(actions);message('预览已准备好。可取消动作、调整组数次数或替换器械；完成后点击保存。');}
  function edited(){const plan=JSON.parse(JSON.stringify(preview));plan.name=get('previewPlanName').value;plan.days.forEach(day=>day.exercises=[]);get('planPreview').querySelectorAll('[data-di]').forEach(card=>{if(!card.querySelector('[data-pick]').checked)return;const ex={...preview.days[card.dataset.di].exercises[card.dataset.ei]};card.querySelectorAll('[data-key]').forEach(input=>ex[input.dataset.key]=input.type==='number'?Number(input.value):input.value);plan.days[card.dataset.di].exercises.push(ex);});plan.days=plan.days.filter(d=>d.exercises.length);return ZerkPlans.validate(plan);}
  function commit(apply){try{const plan=edited();if(!persist(()=>{state.plans=Array.isArray(state.plans)?state.plans:[];const key=origin||plan.name;const existing=state.plans.findIndex(p=>p.key===key);const item={key,url:origin,updatedAt:new Date().toISOString(),plan};if(existing>=0)state.plans[existing]=item;else{if(state.plans.length>=50)throw Error('最多保存 50 个计划，请先移除不需要的计划');state.plans.push(item);}if(apply){for(const day of plan.days){for(const ex of day.exercises){let match=allExercises().find(e=>e.day===day.day&&e.name===ex.name&&e.equipment===ex.equipment);if(!match){match={id:'plan-'+crypto.randomUUID(),day:day.day,name:ex.name,part:ex.part,equipment:ex.equipment,target:ex.sets,custom:true};state.custom.push(match);state.targets[match.id]=ex.sets;state.setProfiles[match.id]={type:ex.type,multiplier:ex.multiplier};state.drafts[match.id]=ex.type==='drop'?{segments:ex.segments}:{weight:'',reps:ex.reps};}state.hidden=state.hidden.filter(id=>id!==match.id);state.selected[day.day]=[...new Set([...(state.selected[day.day]||[]),match.id])];}}}}))return;saved();render();message(apply?'计划已保存并追加到训练。重复动作保留已有目标、重量和记录。':'计划已保存，可离线使用。');get('planPreview').replaceChildren();preview=null;}catch(error){message(error.message);}}
  get('plansBtn').onclick=()=>{saved();get('planURL').value=state.planURL||'';modal.showModal();};get('closePlans').onclick=()=>modal.close();get('capturePlan').onclick=()=>{try{capture();}catch(error){message(error.message);}};
  get('planFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('计划文件需小于 1MB');show(JSON.parse(await file.text()),'');}catch(error){message(error instanceof SyntaxError?'文件不是有效 JSON 计划':error.message);}finally{e.target.value='';}};
  get('fetchPlan').onclick=async()=>{if(busy)return;busy=true;get('fetchPlan').disabled=true;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const url=ZerkPlans.githubURL(get('planURL').value);message('正在读取计划…');const response=await fetch(url,{signal:controller.signal,cache:'no-store',credentials:'omit'});if(!response.ok)throw Error('读取失败：请确认文件存在且仓库公开。私有仓库请下载文件导入。');const body=await response.text();if(body.length>1000000)throw Error('计划文件需小于 1MB');const plan=ZerkPlans.validate(JSON.parse(body));show(plan,url);persist(()=>state.planURL=url);}catch(error){message(error.name==='AbortError'?'读取超时，请检查网络；已保存计划仍可离线使用。':error instanceof SyntaxError?'链接内容不是有效 JSON 计划':error.message);}finally{clearTimeout(timeout);busy=false;get('fetchPlan').disabled=false;}};
})();

